sources:
  npm: true
allowed:
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - isc
  - mit
  - cc0-1.0
  - unlicense
  - 0bsd
reviewed:
  npm:
    - abbrev
    - canvas
    - color-convert
    - fs.realpath
    - glob
    - lodash.deburr
    - minizlib
    - nan
    - rc
    - readable-stream
    - sax
    - sprintf-js
    - string_decoder
